CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, password TEXT, role TEXT, fullname TEXT, mobileno TEXT, email TEXT, cctype TEXT, ccname TEXT, ccno TEXT);

CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT, name TEXT, price INTEGER, qty INTEGER);

CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, uid INTEGER, pid INTEGER, qty INTEGER, amount INTEGER);